---
title: "AFEC-X 2016 data visulization using R"
author: "Zhuangfang Yi, Data Engineer and PhD in Ecological Economics" 
date: "October 7, 2016"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## A bit introduction 

Hi all, Welcome to AFEC-X 2016 class in Xishuangbanna. This is Zhuangfang Yi; I was one of AFEC-X 2009 students. I met most amazing, bright and hardworking people in my class in 2009, who keep inspiring me academically and in my life onward.I still kept in touch most of them, and hope you all enjoy being with each other in the field course and also learned a lot new knowledge on ecology, conservation, and other fancy field design and modeling stuff from your different tutors and classmates.Take as much as you can.

Before we start the classes, I need you guys to start install R and Rstudio. 

## R and R studio installation
To install R, please go to [this site](https://www.r-project.org/), and you could find Rstudio [here](https://www.rstudio.com/products/RStudio/), please install the free desktop version. 


## What I wanna teach you:
- About R, Rstudio,and study resource.
- Data wrangling and visualization, using [Washington DC-bikeshare](https://rpubs.com/Geoyi/BikeshareDC_LM).
- Interactive map and graphs, using [Quake dataset to build web API](https://geoyi.shinyapps.io/quakes3/).
- Machine learning showcase, using [satalite image alignment](https://rpubs.com/Geoyi/TennisCourtAlgrithm).

First 2 sections will be on day one and we will do the last 2 sections on the day two.


## R study resources

- [Getting start with R and RStudio](https://www.youtube.com/watch?v=lVKMsaWju8w);
- [Getting start with R Markdown](https://vimeo.com/142172484);
- Study R from beginer to advanced level @ [DataCamp](https://www.datacamp.com/courses);
- [Data manipulation/wrangling with R and RStudio: Tidyr and Dplyr](https://www.rstudio.com/resources/webinars/data-wrangling-with-r-and-rstudio/);
- R Data visualization with [ggplot2](https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf), [plotly](https://plot.ly/r/), [Shiny](http://shiny.rstudio.com/).
- Additional [statistics and probability study](https://www.khanacademy.org/math/statistics-probability/probability-library)
- [A great TED data talk from Prof. Hans Rosling](https://www.ted.com/talks/hans_rosling_shows_the_best_stats_you_ve_ever_seen)

 Note: some videos are from Youtube, you might need VPN to access them in China
