---
title: "Student_AFEC-X2016"
author: "Zhuangfang Yi"
date: "October 21, 2016"
output: html_document
---
If you wanna understand the dataset, pleas go to the data discription site: https://archive.ics.uci.edu/ml/datasets/Student+Performance
```{r setup, include=FALSE}
setwd("C:/Users/Administrator/Desktop/2016-AFEC-X-R-Data-visualization-master/2016-AFEC-X-R-Data-visualization-master")
list.files("C:/Users/Administrator/Desktop/2016-AFEC-X-R-Data-visualization-master/2016-AFEC-X-R-Data-visualization-master")
# Read CSV, note the delimiter (sep)
df <- read.csv('student-mat.csv',sep=';')
head(df)
```


```{r cars}
summary(df)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
any(is.na(df))
```

```{r}
str(df)
```

```{r}
library(ggplot2)
library(ggthemes)
library(dplyr)
# Grab only numeric columns
num.cols <- sapply(df, is.numeric)
# Filter to numeric columns for correlation
cor.data <- cor(df[,num.cols])
cor.data
```

```{r}
#install.packages('corrgram',repos = 'http://cran.us.r-project.org')
#install.packages('corrplot',repos = 'http://cran.us.r-project.org')
library(corrplot)
library(corrgram)
```
```{r}
corrplot(cor.data,method='color')
```
```{r}
corrgram(df,order=TRUE, lower.panel=panel.shade,
  upper.panel=panel.pie, text.panel=panel.txt)
```

```{r}
ggplot(df,aes(x=G3)) + geom_histogram(bins=20,alpha=0.5,fill='blue') + theme_minimal()
```

```{r}
# Import Library
library(caTools)
# Set a random see so your "random" results are the same as this notebook
set.seed(101) 

# Split up the sample, basically randomly assigns a booleans to a new column "sample"
sample <- sample.split(df$age, SplitRatio = 0.70) # SplitRatio = percent of sample==TRUE

# Training Data
train = subset(df, sample == TRUE)

# Testing Data
test = subset(df, sample == FALSE)

```
```{r}
model <- lm(G3 ~ .,train)
```


```{r}
summary(model)
```

```{r}
# Grab residuals
res <- residuals(model)
# Convert to DataFrame for gglpot
res <- as.data.frame(res)
head(res)
```

```{r}
# Histogram of residuals
ggplot(res,aes(res)) +  geom_histogram(fill='blue',alpha=0.5)

```
```{r}
plot(model)
```
```{r}
G3.predictions <- predict(model,test)
results <- cbind(G3.predictions,test$G3) 
colnames(results) <- c('pred','real')
results <- as.data.frame(results)
```

```{r}
to_zero <- function(x){
    if  (x < 0){
        return(0)
    }else{
        return(x)
    }
}

results$pred <- sapply(results$pred,to_zero)
```

```{r}
mse <- mean((results$real-results$pred)^2)
print(mse)
```

```{r}
mse^0.5
```

```{r}
SSE = sum((results$pred - results$real)^2)
SST = sum( (mean(df$G3) - results$real)^2)

R2 = 1 - SSE/SST
R2

```

